FROM 10.18.16.57/nginx/nginx:1.18.0

RUN echo "Asia/Jakarta" > /etc/timezone
RUN cp /usr/share/zoneinfo/Asia/Jakarta /etc/localtime

ADD ./conf.d   /etc/nginx/conf.d

CMD ["nginx", "-g", "daemon off;"]
